images:
  - name: registry.cn-shanghai.aliyuncs.com/c7n/cibase:0.9.0
    runtime:
      - java-8
      - java-6
      - node-12
      - python-1.1.2

  - name: registry.cn-shanghai.aliyuncs.com/c7n/cibase:0.9.1
    runtime:
      - java-8
      - node-10

before:
  - name: '*auto_devops'
    script:
      - '.auto_devops: &auto_devops |
          http_status_code=`curl -o .auto_devops.sh -s -m 10 --connect-timeout 10 -w %{http_code} "${CHOERODON_URL}/devops/ci?token=${Token}&type=microservice"`
          if [ "$http_status_code" != "200" ]; then
            cat .auto_devops.sh
            exit 1
          fi
          source .auto_devops.sh'
    runtime:
      - java-8
      - node-10
      - java-6

stage:
  - name: release
    script:
      - chart_build
    runtime:
      - java-8
      - node-10
  - name: build
    script:
      - update_pom_version
      - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent test -Dmaven.test.failure.ignore=true -DskipTests=true -U
      - >-
        mvn --batch-mode verify sonar:sonar
        -Dsonar.host.url=$SONAR_URL
        -Dsonar.login=$SONAR_LOGIN
        -Dsonar.gitlab.project_id=$CI_PROJECT_PATH
        -Dsonar.gitlab.commit_sha=$CI_COMMIT_SHA
        -Dsonar.gitlab.ref_name=$CI_COMMIT_REF_NAME
        -Dsonar.analysis.serviceGroup=$GROUP_NAME
        -Dsonar.analysis.commitId=$CI_COMMIT_SHA
        -Dsonar.projectKey=${GROUP_NAME}:${PROJECT_NAME}
      - mvn package spring-boot:repackage
      - mv target/app.jar $PWD/docker
      - kaniko -c $PWD/docker -f $PWD/docker/Dockerfile -d ${DOCKER_REGISTRY}/${GROUP_NAME}/${PROJECT_NAME}:${CI_COMMIT_TAG}
    runtime:
      - java-8
      - node-10

